services:
  # Docker daemon. DNS name "docker"
  docker:
    container_name: jenkins-docker
    image: docker:dind
    restart: always
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - '2376:2376'

  # Jenkins blueocean.
  jenkins-blueocean:
    hostname: jenkins
    depends_on:
      - docker
      - ssh-agent
    container_name: jenkins-blueocean
    build:
      context: .
      dockerfile: ./Dockerfile
      target: jenkins-master
    image: jenkins/jenkins:alpine-jdk21
    #restart: unless-stopped
    restart: always
    networks:
      jenkins:
        aliases:
          - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - VIRTUAL_HOST=jenkins.mobomo.net
      - VIRTUAL_PORT=8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - agent-home:/home/jenkins
    ports:
      - 80:8080
      - 50000:50000
  # Jenkins ssh agent.
  ssh-agent:
    hostname: jenkins.agent
    container_name: jenkins-ssh-agent
    build:
      context: .
      dockerfile: ./agent_Dockerfile
      target: ssh-agent
    image: anairamzap/jenkins-dind-php:jdk21
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=${JENKINS_SLAVE_SSH_PUBKEY}
      - JAVA_HOME=/opt/java/openjdk
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    restart: always
    networks:
      jenkins:
        aliases:
          - jenkins.ssh-agent
          - jenkins.qa-agent-1
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - agent-home:/home/jenkins
    ports:
      - 10000:10000

networks:
  jenkins:
    driver: bridge
volumes:
  jenkins-data:
  jenkins-docker-certs:
  agent-home:
